### ISSUE TITLE
Clippy is broken in CI

### ISSUE THREAD

**Issue by asomers** [dtolnay/serde-yaml#111]
Clippy is no longer running in Travis.  It fails with this error message
```
warning: lint name `clippy` is deprecated and does not have an effect anymore. Use: clippy::all
  |
  = note: requested on the command line with `-D clippy`
```

**Comment by dtolnay** [comment]
Thanks! I believe it was running anyway but the `-Dclippy` command line flag was ignored. Removed in b4812531c37d3154c068888acaaec52214874085 since we already have the following which has the same effect:

https://github.com/dtolnay/serde-yaml/blob/b4812531c37d3154c068888acaaec52214874085/src/lib.rs#L66
