### ISSUE TITLE
{Des,S}erialize not implemented for LinkedHashMap

### ISSUE THREAD

**Issue by CmdrMoozy** [dtolnay/serde-yaml#46]
I'm using serde-yaml to deserialize a custom struct. When I switch to serde 0.9 and serde_yaml 0.6, I get the following sort of error:

```
error[E0277]: the trait bound `linked_hash_map::LinkedHashMap<serde_yaml::Value, serde_yaml::Value>: serde::Deserialize` is not satisfied
 --> src/tests/spec.rs:9:17
  |
9 | #[derive(Debug, Deserialize, Serialize)]
  |                 ^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `linked_hash_map::LinkedHashMap<serde_yaml::Value, serde_yaml::Value>`
  |
  = note: required by `serde::de::SeqVisitor::visit`
```

I tested against a fork of serde-yaml, and I believe the fix is simply to change the linked-hash-map dependency in Cargo.toml to:

```
linked-hash-map = { version = "0.4", features = ["serde_impl"] }
```

(I believe the version bump from 0.3 is worthwhile / harmless, but the serde_impl feature is the key bit here.)

**Comment by dtolnay** [comment]
Can you give a bit more detail on how you are using LinkedHashMap in your project? In particular, what is stopping you from upgrading your own linked-hash-map dependency to 0.4 without worrying about what serde_yaml uses?

**Comment by CmdrMoozy** [comment]
I forked your repository and added a branch with a simple reproduction / example: https://github.com/CmdrMoozy/serde-yaml/tree/issue_46.

The problem is that I want to deserialize a YAML structure which contains some sub-structure that is opaque to me (both its contents and structure vary wildly), so I want to have a serde_yaml::Mapping member of the struct I deserialize into.

However, serde_yaml's dependency on linked_hash_map doesn't enable its serde support, and version 0.3 of linked_hash_map is depending on serde 0.8, so we need to both bump the version and enable the serde_impl feature to get LinkedHashMap to implement Serialize, Deserialize for the right version of serde.

**Comment by dtolnay** [comment]
Rather than bumping the dependency and relying on their Serde impls, I would prefer to go in the direction that serde_json has taken with [`serde_json::Map`](https://docs.serde.rs/serde_json/struct.Map.html) which is an opaque wrapper around an underlying map type. So in our case we would have:

```rust
pub struct Mapping {
    map: LinkedHashMap<Value, Value>,
}

impl Mapping { /* ... */ }
impl Default, Clone, PartialEq, Index, IndexMut, Debug, Extend,
    FromIterator, IntoIterator, Serialize, Deserialize for Mapping { /* ... */ }
```

This way we avoid tying the serde_yaml public API to a particular version of linked-hash-map and we can swap out the underlying implementation transparently when linked-hash-map makes breaking changes or is superseded by a different library.

Would you be able to submit a PR for this change?

**Comment by CmdrMoozy** [comment]
Sure, I'll send a PR later today.
