### ISSUE TITLE
Invalid examples in docs

### ISSUE THREAD

**Issue by RazrFalcon** [dtolnay/serde-yaml#75]
https://docs.rs/serde_yaml/0.7.1/serde_yaml/enum.Value.html#method.get

```rust
let object: Value = yaml(r#"{ A: 65, B: 66, C: 67 }"#);
```

```rust
  --> src/main.rs:17:25
   |
17 |     let object: Value = yaml(r#"{ A: 65, B: 66, C: 67 }"#);
   |                         ^^^^ not found in this scope
```

**Comment by killercup** [comment]
The doc example is perfectly fine (doc examples get run as tests), this one just doesn't show everything! 😉 The motivation to hide this is that it is about how to use `Value::get` method, and the boilerplate code to create this `Value` is not important. You can click the `[src]` link and see the full code of the doc example:

https://github.com/dtolnay/serde-yaml/blob/e12507ad6ac001ac97f0143943fa1a935d7d0514/src/value/mod.rs#L90-L145

The code example lines starting with `# ` are omitted in the rendered docs.

**Comment by RazrFalcon** [comment]
I see. I know this trick, but it makes examples "non-copy-paste-able".

Also, pretty misleading, since I spent some time looking for a `yaml` method in docs.

**Comment by killercup** [comment]
Yeah, I can see how that is misleading… sorry about that. In retrospect I don't think that function pulls its own weight and I'm totally okay with replacing the `yaml("foo")` calls with `serde_yaml::from_str("foo").unwrap()`. Would you like to make a pull request? :)

By the way, In general I do not think doc examples need to work as standalone code. It is nice when they do, but I'd probably err on the side of conciseness of copy-paste-ability. (This is a similar discussion as the one about using `?` or `unwrap` in examples: I'd really like to just use `?` everywhere instead of implicitly telling people that `unwrap` is okay…)

**Comment by RazrFalcon** [comment]
According to [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark), you can use `?` in examples, but it's pain to write. So I'm still using `unwrap()`.

And again, `?` makes examples "non-copy-paste-able"...

I'm personally prefer `serde_yaml::from_str("foo").unwrap()`. And `serde_json` [uses](https://docs.rs/serde_json/1.0.3/serde_json/enum.Value.html#method.get) a similar approach. But they have a nice `json!()` macro.
